"""
Abstract Strategy Base Interface & Signal Schema.
Ensures every trading signal explicitly accounts for capital feasibility and fee drag.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
import time
from typing import Literal, Optional
from market_data.normalizer import MarketTick
from market_data.orderbook import OrderbookSnapshot


@dataclass(frozen=True)
class TradingSignal:
    """Standardized trading or arbitrage signal generated by a research strategy."""
    signal_id: str
    timestamp_ms: float
    strategy_name: str
    symbol: str
    action: Literal["BUY", "SELL", "HOLD"]
    order_type: Literal["MARKET", "LIMIT"]
    suggested_price: float
    quantity: int
    stop_loss_price: Optional[float] = None
    target_price: Optional[float] = None
    confidence: float = 1.0  # 0.0 to 1.0
    is_capital_feasible: bool = True  # True if fits within ₹3,000 capital
    infeasibility_reason: Optional[str] = None
    metadata: dict = field(default_factory=dict)


class BaseStrategy(ABC):
    """Abstract base class for all algorithmic and arbitrage research strategies."""

    def __init__(self, name: str):
        self.name = name
        self.is_active: bool = True

    @abstractmethod
    def on_tick(self, tick: MarketTick) -> list[TradingSignal]:
        """Process incoming normalized market tick."""
        pass

    @abstractmethod
    def on_orderbook(self, snapshot: OrderbookSnapshot) -> list[TradingSignal]:
        """Process incoming orderbook snapshot with micro-price and depth."""
        pass
